services:
  - type: web
    name: word-segmentation
    env: node
    plan: starter
    # Update the following line with your Strapi GitHub repo
    repo: https://github.com/OpenPecha/pecha-tool-for-word-segmentation
    branch: main
    buildCommand: npm ci --production=false && npm run build && npm prune --production
    startCommand: npx prisma migrate deploy && npm run start
    envVars:
      - key: NODE_VERSION
        value: ~16.14.2
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: word-segmentation-pg
          property: connectionString

databases:
  - name: word-segmentation-pg
    plan: starter
